// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA84OPVOsrE5_gD0wGWVOdTOQOcojTcdUc',
    appId: '1:319679596796:web:280470dee85055b60f2f79',
    messagingSenderId: '319679596796',
    projectId: 'whatsapp-clone-2924f',
    authDomain: 'whatsapp-clone-2924f.firebaseapp.com',
    storageBucket: 'whatsapp-clone-2924f.appspot.com',
    measurementId: 'G-2J9JLQ2Z6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBcODKatexPmITFRPpZI659Uurb-GV2gs',
    appId: '1:319679596796:android:905c1fc9d56a374d0f2f79',
    messagingSenderId: '319679596796',
    projectId: 'whatsapp-clone-2924f',
    storageBucket: 'whatsapp-clone-2924f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAamS6hzMJ4W726_Aq5IqVCrQ40NlyaFq8',
    appId: '1:319679596796:ios:7b2566221171a3ba0f2f79',
    messagingSenderId: '319679596796',
    projectId: 'whatsapp-clone-2924f',
    storageBucket: 'whatsapp-clone-2924f.appspot.com',
    iosClientId: '319679596796-vjihqjkqdeh5kv4teoepadl6olgodftv.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAamS6hzMJ4W726_Aq5IqVCrQ40NlyaFq8',
    appId: '1:319679596796:ios:7b2566221171a3ba0f2f79',
    messagingSenderId: '319679596796',
    projectId: 'whatsapp-clone-2924f',
    storageBucket: 'whatsapp-clone-2924f.appspot.com',
    iosClientId: '319679596796-vjihqjkqdeh5kv4teoepadl6olgodftv.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );
}
